#!/bin/sh

if ! $(git diff --quiet && git diff --cached --quiet) ; then
  git config --local user.email "mathieu@dutour.me"
  git config --local user.name "Submodule updater"

  git add refined-github
  git commit -m "Update refined-github :arrow_up:"

  git --no-pager log -1

  TAG_VERSION="$(./node_modules/.bin/utc-version --apple)"
  git tag $TAG_VERSION

  git remote add deploy https://${GH_TOKEN}@github.com/mathieudutour/refined-github-safari.git > /dev/null 2>&1
  git push deploy master
  git push deploy $TAG_VERSION
fi
